version: '3.8'

services:
  app:
    build:
      target: production
    ports:
# Ports is HOST:CONTAINER
# CONTAINER had to be 3000
# HOST can be change by the port you want to expose
      - "5000:3000"
    volumes:
      - configuration-db:/app/database
      - type: bind
        source: ./config.json
        target: /app/config.json
    command: npm run start
volumes:
  configuration-db:
