CREATE TABLE IF NOT EXISTS sensors (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    sensor_id TEXT UNIQUE,
    label TEXT
);

CREATE TABLE IF NOT EXISTS types (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	type_id TEXT NOT NULL,
	label TEXT
);

CREATE TABLE IF NOT EXISTS types_by_sensor (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	sensor_id TEXT NOT NULL,
	type_id TEXT NOT NULL,
	UNIQUE(sensor_id, type_id)
)